runtime: python27
api_version: 1
threadsafe: true
instance_class: B1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 60 # Permissable range 8-80

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /bower
  static_dir: bower

# Ensure login required for birthday section
- url: /birthday.*
  script: main.app
  login: required

# Secure cron jobs against public consumption
- url: /tasks.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]